Allow remote launch to control hostname of remote targets matching the configuration tree

diff --git a/tools/ots_remote_start b/tools/ots_remote_start
--- a/tools/ots_remote_start
+++ b/tools/ots_remote_start
@@ -5,30 +5,42 @@ SCRIPT_DIR="$(
  pwd -P 
 )"
 
+
+# # Bash defines HOSTNAME but it's possible that it might not be a FQDN, this specifically enforces that it will be
+HOSTNAME="$(hostname -f)"
+
+THIS_HOST="$1"
+if [ "x$1" == "x" ]; then
+	THIS_HOST="${HOSTNAME}"
+else
+  shift
+fi
+
 # Get color code variables
 source ${SCRIPT_DIR}/common.sh ots_remote_start
 
+
 STARTTIME=`date +"%d%h%y.%T"` #to fully ID one StartOTS from another
-out "${Green}=========================== ots REMOTE ============================="
+out "${Green}=========================== ots REMOTE on {${THIS_HOST}} ============================="
 info "ots script path = ${SCRIPT_DIR}/ots_remote_start"
 info "Expected setup path     = ${SCRIPT_DIR}/../../../../setup_ots.sh"
 
 
 # Have to CD because setup_ots.sh isn't safe to run in other directories than the ots root, die if it didn't work
-cd ${SCRIPT_DIR}/../../../ || die "Couldn't chdir to ots setup directory on ${HOSTNAME}"
+cd ${SCRIPT_DIR}/../../../ || die "Couldn't chdir to ots setup directory on ${THIS_HOST}"
 if ! [ -e setup_ots.sh ]; then # try going one directory up (for mrb reverse compatibility)
-  cd ../ || die "Couldn't chdir to ots setup directory on ${HOSTNAME}"
+  cd ../ || die "Couldn't chdir to ots setup directory on ${THIS_HOST}"
 fi
 
 # We don't care about the non-error output of this script because it gets shown on the remote's launching terminal
 userinput="$(cat .ots_setup_type.txt)";
-source ./setup_ots.sh >/dev/null </dev/null || die "Couldn't setup ots for ${userinput} on ${HOSTNAME}"
+source ./setup_ots.sh >/dev/null </dev/null || die "Couldn't setup ots for ${userinput} on ${THIS_HOST}"
 
-info "Executing ots script on ${HOSTNAME}"
+info "Executing ots script on ${THIS_HOST}"
 
 # -x is a special "remote launch" flag to handle that similarly to the -s case but with less printouts
 # Exec since this is the last thing this script does and we don't need a pointless fork (plus the process stays the same for ssh)
-exec ots -x || die "Couldn't launch ots on ${HOSTNAME}"
+exec ots -x || die "Couldn't launch ots on ${THIS_HOST}"
 
 
 
